site_name: "MSE-Outreach"
repo_name: https://github.com/nrdavid/MSE-Outreach

theme:
  name: material
  custom_dir: overrides/
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.integrate
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.share
    - announce.dismiss
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode toggle
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep blue
      accent: yellow
    # Dark mode toggle
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: yellow
      
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: nrdavid
      repo: whsun-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md

  - About Us:
  

  - Classroom Demos (1-2 hrs):
    - Battery Lab: 'classroom_demos/battery_lab.md'
    - Chocolate Tempering: 'classroom_demos/chocolate_tempering.md'
    - Crystal Growth: 'classroom_demos/crystal_growth.md'
    - Hydrogels: 'classroom_demos/hydrogels.md'
  - Shorter MSE Demos (5-15 mins):
    - Tempering Bobby Pins: 'smaller_demos/tempering_bobby.md'
  - About Us:
    - Who Are We?: 'about_us/who_are_we.md'
    - Contact Us: 'contact_us.md'


markdown_extensions:
  - attr_list
  - md_in_html
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nrdavid/MSE-Outreach
  generator: false
  extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true